theme = "tokyonight"

[editor]
bufferline = "always"
cursorline = true
line-number = "relative"
rulers = [120]
true-color = true
end-of-line-diagnostics = "warning"

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
character = "╎"
render = true

[keys.normal]
X = "select_line_above"
H = "goto_previous_buffer"
L = "goto_next_buffer"

[keys.select]
X = "select_line_above"
